#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
themesDir="${scriptDir}/themes"
palettesDir="${scriptDir}/palettes"
source $scriptDir'/lib/lib'

detailed=0
for arg in "$@"; do
  if [ "$arg" = "--detailed" ]; then
    detailed=1
    break
  fi
done

clear
printf "\033[48;5;4m"
center_string Palettes
no_color_esc

if [ $detailed -eq 1 ]; then

  for FILE in $(ls $palettesDir); 
    do 
    if [ $FILE != 'README.md' ]
    then
      printf "\033[3m"
      printf "\033[48;5;17m"
      center_string $FILE
      no_color_esc
      echo 
      source $palettesDir/$FILE

      prepare_colors

      printf "\033[1mMain colors$(no_color_esc)\n\n"
      printf "Primary     "
      printf "$(rgb_bg_esc $palette_primary)   $(no_color_esc)  "
      printf "$(rgb_bg_esc $palette_primary_dark)   $(no_color_esc)  \n\n"
      printf "Secondary   "
      printf "$(rgb_bg_esc $palette_secondary)   $(no_color_esc)  "
      printf "$(rgb_bg_esc $palette_secondary_dark)   $(no_color_esc)      \n\n"
      printf "Accent      "
      printf "$(rgb_bg_esc $palette_accent)   $(no_color_esc)  "
      printf "$(rgb_bg_esc $palette_accent_dark)   $(no_color_esc) \n\n"

      printf "\033[1mGradient$(no_color_esc)\n\n"

      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end ' ')  $(no_color_esc)"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '  ')  $(no_color_esc)"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '   ')  $(no_color_esc)"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '    ')  $(no_color_esc)"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '       ')  $(no_color_esc) \n\n"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '          ')  $(no_color_esc)"
      printf "$(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '                ')  $(no_color_esc)\n\n"

      printf "\033[1mVariants$(no_color_esc)\n\n"
      printf "$(rgb_bg_esc $palette_variant_1)   $(no_color_esc)  "
      printf "$(rgb_bg_esc $palette_variant_2)   $(no_color_esc)  "
      printf "$(rgb_bg_esc $palette_variant_3)   $(no_color_esc)  -  "

      printf "$(rgb_bg_esc $palette_variant_1) $(no_color_esc)"
      printf "$(rgb_bg_esc $palette_variant_2) $(no_color_esc)"
      printf "$(rgb_bg_esc $palette_variant_3) $(no_color_esc)"
      printf '\n\n'

      printf "\033[1mText color:$(no_color_esc) $(rgb_fg_esc $palette_text)this is the stdin text color$(no_color_esc) "

      no_color_esc
      echo
      echo
    fi
  done

else

  for FILE in $(ls $palettesDir); 
    do 
    if [ $FILE != 'README.md' ]
    then
      printf "\033[3m"
      printf "\033[48;5;17m"
      no_color_esc
      printf "\n"
      source $palettesDir/$FILE
      prepare_colors

      printf "%-10s %s\n" $FILE "$(rgb_bg_esc $palette_primary)  $(no_color_esc)  $(rgb_bg_esc $palette_secondary)  $(no_color_esc)  $(rgb_gradient_esc $palette_gradient_start $palette_gradient_end '    ')"
      printf "$(no_color_esc) "
      echo

    fi
  done
fi