#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
themesDir="${scriptDir}/themes"
palettesDir="${scriptDir}/palettes"
source $scriptDir'/lib/lib'

detailed=0
for arg in "$@"; do
  if [ "$arg" = "--detailed" ]; then
    detailed=1
    break
  fi
done

clear
printf "\033[48;5;4m"
center_string Palettes
no_color

if [ $detailed -eq 1 ]; then

  for FILE in $(ls $palettesDir); 
    do 
    if [ $FILE != 'README.md' ]
    then
      printf "\033[3m"
      printf "\033[48;5;17m"
      center_string $FILE
      no_color
      echo 
      source $palettesDir/$FILE

      printf "\033[1mMain colors$(no_color)\n\n"
      printf "Primary     "
      printf "$(rgb_bg $palette_primary)   $(no_color)  "
      printf "$(rgb_bg $palette_primary_dark)   $(no_color)  \n\n"
      printf "Secondary   "
      printf "$(rgb_bg $palette_secondary)   $(no_color)  "
      printf "$(rgb_bg $palette_secondary_dark)   $(no_color)      \n\n"
      printf "Accent      "
      printf "$(rgb_bg $palette_accent)   $(no_color)  "
      printf "$(rgb_bg $palette_accent_dark)   $(no_color) \n\n"

      printf "\033[1mGradient$(no_color)\n\n"

      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end ' ')  $(no_color)"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '  ')  $(no_color)"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '   ')  $(no_color)"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '    ')  $(no_color)"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '       ')  $(no_color) \n\n"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '          ')  $(no_color)"
      printf "$(bg_gradient $palette_gradient_start $palette_gradient_end '                ')  $(no_color)\n\n"

      printf "\033[1mVariants$(no_color)\n\n"
      printf "$(rgb_bg $palette_variant_1)   $(no_color)  "
      printf "$(rgb_bg $palette_variant_2)   $(no_color)  "
      printf "$(rgb_bg $palette_variant_3)   $(no_color)  -  "

      printf "$(rgb_bg $palette_variant_1) $(no_color)"
      printf "$(rgb_bg $palette_variant_2) $(no_color)"
      printf "$(rgb_bg $palette_variant_3) $(no_color)"
      no_color
      echo
      echo
    fi
  done

else

  for FILE in $(ls $palettesDir); 
    do 
    if [ $FILE != 'README.md' ]
    then
      printf "\033[3m"
      printf "\033[48;5;17m"
      no_color
      printf "\n"
      source $palettesDir/$FILE

      printf "%-10s %s\n" $FILE "$(rgb_bg $palette_primary)  $(no_color)  $(rgb_bg $palette_secondary)  $(no_color)  $(bg_gradient $palette_gradient_start $palette_gradient_end '    ')"
      printf "$(no_color) "
      echo
    fi
  done
fi