#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
themesDir="${scriptDir}/themes"

clear

printf "\033[48;5;4m"
echo -e "                      Themes demo                     \033[0m"
for FILE in $(ls $themesDir); 
  do 
  if [ $FILE != 'README.md' ] && [ $FILE != 'to_refactor' ] && [ $FILE != 'generic' ] && [ $FILE != 'non_generic' ] && [ $FILE != 'palettes' ]
  then
    printf "\033[3m"
    printf "\033[48;5;17m"
    echo -e "        ${FILE}        "
    printf "\033[0m"
    source $themesDir/$FILE
    eval $PROMPT_COMMAND
    PS1_EVAL=$(eval "echo \"$PS1\"")
    PS1_EVAL=$(echo "$PS1_EVAL" | sed 's/\\\[//g;s/\\\]//g')
    echo -e "$PS1_EVAL"
    printf "\033[0m"
    echo
    echo
  fi
done

printf "\033[48;5;17m"
echo -e "                                                       \033[0m"