#!/bin/bash
PRIMARY="\[\e[38;5;197m\]"
SECONDARY='\[\033[38;5;165m\]'
THIRD='\[\033[38;5;214m\]'
NC='\[\033[0m\]'

grad() {
  COUNTER=0
  COLOR=$1
  COLS=$2
  TXT=${*:3}
  MOD="$(($((${#TXT}/${COLS}))*2))"
  if [ $MOD == 0 ]
  then
	  MOD=1
  fi
  for (( i=0; i<${#TXT}; i++ )); do  
    printf "\e[38;5;${COLOR}m${TXT:COUNTER:1}"
    COUNTER=$(expr $COUNTER + 1)
    if [ $((i%$MOD)) == 0 ]
    then 
      COLOR=$(expr $COLOR + 1)
    fi
  done
}

p() {
  TEXT=$1
  printf "$PRIMARY${TEXT}${NC}"
}
s() {
  TEXT=$1
  printf "${SECONDARY}${TEXT}${NC}"
}
t() {
  TEXT=$1
  printf "${THIRD}${TEXT}${NC}"
}

c() {
  COLOR=$1
  printf "\[\e[30;48;5;${COLOR}m\] ${NC}"
}

datetime() {
	A=$(date "+%A %d %B %Y %T")
	printf "$A"
}

export PS1="$(c 161) $(grad 197 5 $USER) $(t '>>') $(p '$(grad 196 7 $(pwd))') \r\n$(c 162) $(p '$(grad 197 6 $(datetime))')$(s '$(git branch 2>/dev/null | grep '^*' | colrm 1 1)' ) \r\n$(c 163) $(t '\$ ')"
