#!/usr/bin/bash

MAIN_COLOR="\[\033[38;5;88m\]";
SECONDARY_COLOR="\[\033[38;5;238m\]";
ACCENT_COLOR="\[\033[38;5;124m\]";
TEXT_COLOR="\[\033[38;5;246m\]";


grad() {
  COUNTER=0;
  COLOR=$1;
  COLS=$2;
  TXT=${*:3};
  MOD="$(($((${#TXT}/${COLS}))*2))"
  if [ $MOD == 0 ]
  then
	  MOD=1
  fi
  for (( i=0; i<${#TXT}; i++ )); do  
    printf "\e[38;5;${COLOR}m${TXT:COUNTER:1}"
    COUNTER=$(expr $COUNTER + 1)
    if [ $((i%$MOD)) == 0 ]
    then 
      COLOR=$(expr $COLOR + 1)
    fi
  done
}

PROMPT_COMMAND='pwd2=$(sed "s:\([^/]\)[^/]*/:\1/:g" <<<$PWD);\
gitbranch=$(git branch 2>/dev/null | grep '^*' | cut -c 2-);\
FIRST_LINE="$MAIN_COLOR┌───( $USERNAME $MAIN_COLOR)-[ $(grad 234 10 $pwd2) $MAIN_COLOR]"; \
SECOND_LINE="│$SECONDARY_COLOR \d \t $MAIN_COLOR"; \
LAST_LINE="└─$gitbranch$ACCENT_COLOR λ $TEXT_COLOR"; \
PS1="\r\n${FIRST_LINE}\r\n${SECOND_LINE} \r\n${LAST_LINE}" '
