#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")

for FILE in $(ls $scriptDir/themes); 
  do 
  if [ $FILE != 'README.md' ] && [ $FILE != 'to_refactor' ]
  then
    echo $FILE
    source $scriptDir/themes/$FILE
    eval $PROMPT_COMMAND
    PS1_EVAL=$(eval "echo \"$PS1\"")
    PS1_EVAL=$(echo "$PS1_EVAL" | sed 's/\\\[//g;s/\\\]//g')
    echo -e "$PS1_EVAL"
    read
  fi
done