#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../../lib/lib'
prepare_colors

prompt_cmd() {
  TMP_GIT_BRANCH="$(gitbranch)"
  LINE_1="$(rgb_gradient $color_1 $color_3 '┌───( '$USERNAME$USER@$HOSTNAME' )-[ '$(basename $PWD)' ]')"
  LINE_2="$(rgb_fg $color_1_1)│ $(rgb_gradient $color_1 $color_3 $(short_datetime)) $(rgb_fg $color_accent)~ $(rgb_gradient $color_2 $color_3 $TMP_GIT_BRANCH)"
  LINE_3="$(rgb_fg $color_1_2)└─$(rgb_fg $color_accent) λ $(rgb_fg $color_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
