#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../../lib/lib'
prepare_colors

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(xterm_bg ${color_xterm}) $(no_color) $(rgb_gradient $color_1 $color_3 $USERNAME@$HOSTNAME)$(rgb_fg $color_accent) >> $(rgb_gradient $color_1 $color_3 $(basename $PWD)) "
  LINE_2="$(xterm_bg $((color_xterm + 1))) $(no_color) $(rgb_gradient $color_1 $color_3 $DATETIME_1 $(gitbranch))"
  LINE_3="$(xterm_bg $((color_xterm + 2))) $(no_color) $(rgb_fg $color_accent)$ $(rgb_fg $rgb_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
