#!/bin/bash
grad() {
  COUNTER=0
  COLOR=$1
  COLS=$2
  TXT=${*:3}
  MOD="$(($((${#TXT}/${COLS}))*2))"
  if [ $MOD == 0 ]
  then
	  MOD=1
  fi
  for (( i=0; i<${#TXT}; i++ )); do  
    printf "\e[38;5;${COLOR}m${TXT:COUNTER:1}"
    COUNTER=$(expr $COUNTER + 1)
    if [ $((i%$MOD)) == 0 ]
    then 
      COLOR=$(expr $COLOR + 1)
    fi
  done
}