#!/bin/bash
grad2() {
  start_color=$1
  end_color=$2
  str=$3
  str_len=${#str}

  IFS=',' read r1 g1 b1 <<< "$start_color"
  IFS=',' read r2 g2 b2 <<< "$end_color"

  dr=$((r2 - r1))
  dg=$((g2 - g1))
  db=$((b2 - b1))

  rstep=$((dr / str_len))
  gstep=$((dg / str_len))
  bstep=$((db / str_len))

  for i in $(seq 0 $((str_len - 1))); do
    r3=$((r1 + rstep*i))
    g3=$((g1 + gstep*i))
    b3=$((b1 + bstep*i))
    printf "\[\033[38;2;${r3};${g3};${b3}m\]${str:i:1}"
  done
  printf "\[\033[0m\]"

}

