#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'

color_1="27;207;198"
color_2="41;130;255"
color_2_light="79;166;247"
color_3="207;171;27"
text_color="210;210;210"

prompt_cmd() {
  FIRST_LINE="$(rgb_gradient $color_1 $color_2 '┌───( '$USERNAME$USER@$HOSTNAME' )-[ '$(basename $PWD)' ]')"

  SECOND_LINE="$(ansi $color_1)│ $(short_datetime) $(ansi $color1)"

  LAST_LINE="$(ansi $color_1)└─$(ansi $color_2_light)$(gitbranch)$(ansi $color_3) λ $(ansi $text_color)"

  PS1="\r\n${FIRST_LINE}\r\n${SECOND_LINE} \r\n${LAST_LINE}"
}

export PROMPT_COMMAND='prompt_cmd'
