#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'

rgb_1="27;207;198"
rgb_2="149;79;255"
rgb_3="207;171;27"
rgb_4="143;152;255"
rgb_text="225;225;225"
xterm_1=36
xterm_2=37
xterm_3=38

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(xterm_bg ${xterm_1}) $(no_color) $(rgb_gradient $rgb_1 $rgb_4 $USERNAME@$HOSTNAME)$(rgb_fg $rgb_3) >> $(rgb_gradient $rgb_1 $rgb_4 $(basename $PWD)) "
  LINE_2="$(xterm_bg ${xterm_2}) $(no_color) $(rgb_gradient $rgb_1 $rgb_4 $DATETIME_1 $(gitbranch))"
  LINE_3="$(xterm_bg ${xterm_3}) $(no_color) $(rgb_fg $rgb_3)$ $(rgb_fg $rgb_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
