#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'
prepare_colors

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(rgb_bg $palette_variant_1) $(no_color) $(rgb_gradient $palette_gradient_start $palette_gradient_end $(current_user)@$HOSTNAME '>>' $(basename $PWD)) "
  LINE_2="$(rgb_bg $palette_variant_2) $(no_color) $(rgb_gradient $palette_gradient_start $palette_gradient_end $DATETIME_1 $(gitbranch))"
  LINE_3="$(rgb_bg $palette_variant_3) $(no_color) $(rgb_fg $palette_accent)$ $(rgb_fg $palette_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
