#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'
prepare_colors



prompt_cmd() {
  TMP_GIT_BRANCH="$(gitbranch)"
  LINE_1="$(rgb_fg $color_primary_variant_1)┌───( $(rgb_fg $color_primary)$(current_user)@$HOSTNAME $(rgb_fg $color_primary_variant_1))-[ $(rgb_fg $color_secondary)$(basename $PWD)$(rgb_fg $color_primary_variant_1) ]"
  LINE_2="$(rgb_fg $color_primary_variant_1)│ $(rgb_fg $color_secondary)$(short_datetime) $(rgb_fg $color_accent)~ $(rgb_fg $color_secondary)$TMP_GIT_BRANCH"
  LINE_3="$(rgb_fg $color_primary_variant_1)└─$(rgb_fg $color_accent) λ $(rgb_fg $color_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'

