#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'
prepare_colors

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(rgb_bg $palette_primary)  $(no_color) $(rgb_gradient $palette_gradient_start $palette_gradient_end $(current_user))$(rgb_fg $palette_accent) >> $(rgb_fg $palette_secondary)$(dirs) "
  LINE_2="$(rgb_bg $palette_primary)  $(no_color) $(rgb_fg $palette_primary)$(short_date) $(rgb_fg $palette_primary_dark)$(short_time) $(rgb_fg $palette_accent)λ"

  PS1="\r\n${LINE_1}\r\n${LINE_2}"
}

export PROMPT_COMMAND='prompt_cmd'
