#!/bin/bash
color_primary="#B30000"
color_secondary="#620014"
color_accent="#565656"
color_primary_variant_1="#8a0907"
color_primary_variant_2="#750000"
color_primary_variant_3="#680000"
color_text="#bdbdbd"

