#!/bin/bash
color_primary="#f7a305"
color_secondary="#d700ff"
color_accent="#f7a305"
color_primary_variant_1="#ec596a"
color_primary_variant_2="#e8448b"
color_primary_variant_3="#e42eac"
color_text="#d2d2d2"
