#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'

rgb_1="255;0;95"
rgb_2="215;0;135"
rgb_3="255;175;0"
rgb_4="215;0;255"
rgb_text="225;225;225"
xterm_1=161
xterm_2=162
xterm_3=163

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(256_bg_ps1 ${xterm_1}) $(no_color_ps1) $(fg_gradient_ps1 $rgb_1 $rgb_4 $USERNAME@$HOSTNAME)$(rgb_fg_ps1 $rgb_3) >> $(fg_gradient_ps1 $rgb_1 $rgb_4 $(basename $PWD)) "
  LINE_2="$(256_bg_ps1 ${xterm_2}) $(no_color_ps1) $(fg_gradient_ps1 $rgb_1 $rgb_4 $DATETIME_1 $(gitbranch))"
  LINE_3="$(256_bg_ps1 ${xterm_3}) $(no_color_ps1) $(rgb_fg_ps1 $rgb_3)$ $(rgb_fg_ps1 $rgb_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
